import { Event } from 'https://raw.githubusercontent.com/fac-31/Pro0428-LocalEventShared/main/src/models/event.model.ts';

// Test event examples
export const testEvents: Event[] = [
  {
    mode: 'music',
    name: 'Finsbury Park Festival 2025',
    description: 'Annual music festival in the park',
    location: 'Finsbury Park',
    date: '2025-06-15T19:00:00.000Z',
    price: 25,
    distance: 10,
    url: 'https://example.com/festival',
  },
  {
    mode: 'music',
    name: 'Finsbury Park Festival',
    description: 'music festival in the park',
    location: 'Finsbury Park',
    date: '2025-06-15T19:00:00.000Z',
    price: 25,
    distance: 10,
    url: 'https://example.com/festival',
  },
  {
    mode: 'music',
    name: 'FINSBURY PARK FESTIVAL - 2025 Edition',
    description: 'The biggest festival in Finsbury Park',
    location: 'Finsbury Park',
    date: '2025-06-15T19:00:00.000Z',
    price: 25,
    distance: 10,
    url: 'https://example.com/festival',
  },
  {
    mode: 'music',
    name: 'Jazz in the Park - June 15th',
    description: 'Jazz concert in the park',
    location: 'Finsbury Park',
    date: '2025-06-15T19:00:00.000Z',
    price: 15,
    distance: 10,
    url: 'https://example.com/jazz',
  },
  {
    mode: 'sports',
    name: 'Finsbury Marathon 2025',
    description: 'Annual marathon through Finsbury',
    location: 'Finsbury Park',
    date: '2025-07-10T08:00:00.000Z',
    price: 30,
    distance: 10,
    url: 'https://example.com/marathon',
  },
];
