GET http://localhost:3000/users/all 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODJhMGM1MjYwZjMzOTA1ZDE2Y2RhMjciLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsIm5hbWVfZmlyc3QiOiJBZG1pbiIsIm5hbWVfbGFzdCI6IlVzZXIiLCJzYXZlZF9ldmVudHMiOltdLCJyb2xlIjoiYWRtaW4ifQ.f6mNh1BrmJfLtN74x-lmivdnI6ejgajvCHaCunxn-48