GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODJiM2ViZGY2NjdmNmEwMWZjZWUxMWUiLCJlbWFpbCI6IkRramRoc2JmamV3cmJrQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiRG9uYWxkLWtqaHNkYnZjY2siLCJzYXZlZF9ldmVudHMiOltdfQ.OKCbLB1P7PIUMb29dqOZrynbkYFdbKPkwgKBU5-E-Go

