GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIzODIwMzRhOGRiZjIxTE2Y2FkN2MiLCJlbWFpbCI6ImR1Y2tAZ21haWwuY29tIiwic2F2ZWRfZXZlbnRzIjpbXX0.FRXlEKwI14gpyD0vQijyeWGjWDn7DBCUnXOKis0uXXE

