GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODQ2YmYyOTgzNmUxNzYxOTg3YWQ1OGUiLCJlbWFpbCI6InVzZXJ1cGRhdGV0ZXN0QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoib2xkLXBhc3dvcmQiLCJzYXZlZF9ldmVudHMiOltdLCJyb2xlIjoidXNlciJ9.fekG7xhKL-IsmNi0S7088ZsouULj7zsWDCX2X0jZ-8g

