name: Trigger Deno Deploy Daily Job

on:
  # schedule:
  #    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger daily task
        run: 'curl -H "X-Daily-Token: ${{ secrets.DAILY_JOB_TOKEN }}" https://your-deploy-url.deno.dev/'

        Deno.cron("sample cron", "*/10 * * * *", () => {
  console.log("cron job executed every 10 minutes");
});